# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 22:33
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neigbor_hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor_hood',
            name='json',
            field=jsonfield.fields.JSONField(default={'coordinates': [-1.4058208465576172, 47.15301133231325], 'type': 'Point'}),
        ),
    ]
